[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
rumqttc = "0.24"
rumqttd = "0.19"
tokio = { version = "1", features = ["full"] }
tracing-subscriber = { version = "0.3", default-features = false }
config = "0.14.0"
