[workspace]
members = [ "crates/*" ]
resolver = "2"

[workspace.dependencies]
config = "0.14.0"
rumqttc = "0.24"
rumqttd = "0.19"
rust-embed = "8.5.0"
tokio = { version = "1", features = ["full"] }
tracing-subscriber = { version = "0.3", default-features = false }
