[package]
name = "client"
version = "0.0.0"
edition = "2021"

[dependencies]
rumqttc = { workspace = true }
tokio = { workspace = true }
tracing-subscriber = { workspace = true }
config = { workspace = true }

[[bin]]
name = "client"
path = "src/main.rs"
