[package]
name = "broker"
version = "0.0.0"
edition = "2021"

[dependencies]
rumqttd = { workspace = true }
tokio = { workspace = true }
tracing-subscriber = { workspace = true }
shared = { path = "../shared" }

[[bin]]
name = "broker"
path = "src/main.rs"
