[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
config = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
rust-embed = { workspace = true }
rumqttc = { workspace = true }
rumqttd = { workspace = true }
